### PR TITLE
Add support for zsh terminals

### PR DESCRIPTION
**Pull request by mhdcodes**
## Description 

I have added some support for ZSH terminals following: (https://github.com/paulirish/git-open)

### Changes

- Add support for ZSH
- Apply some markdown lint fixes

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@mohammed-elhaouari thanks for the first contribution! ⭐ 

For clarity, this does work on ZSH given the current instruction. However, this is a way to add it as a ZSH "plugin"?

**Comment by mhdcodes** [comment]
Yes @jasonmccreary. It is to add it as plugin to `oh-my-zsh`.

I didn't explore the other possibilities (zgen, zplug, antigen ...)

**Comment by jasonmccreary** [comment]
@mohammed-elhaouari, no worries. This is a good start to add support for `oh-my-zsh`. I haven't used the others myself, but I assume I could copy the same setup from `git-open`. However, I'll let others make the contribution.

Let me know this worked for you now that it's merged.

**Comment by mhdcodes** [comment]
@jasonmccreary I agree with you on that.

Works like charm.
image

**Pull request merged**
